### ISSUE TITLE
NumPy not working

### ISSUE THREAD

**Issue by Maris495** [Zarxrax/Cutie-Roto#6]
I've tried to run Cutie-Roto after installing the dependencies, but I keep getting this error, especially after I installed numpy<2. Any solutions to this?

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\username\Downloads\Programs\Cutie-Roto\cutie_roto.py", line 21, in <module>
    from gui.main_controller import MainController
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\gui\main_controller.py", line 12, in <module>
    from torchvision.transforms.functional import to_tensor
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torchvision\ops\roi_align.py", line 4, in <module>
    import torch._dynamo
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\__init__.py", line 64, in <module>
    torch.manual_seed = disable(torch.manual_seed)
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\decorators.py", line 50, in disable
    return DisableContext()(fn)
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\eval_frame.py", line 410, in __call__
    (filename is None or trace_rules.check(fn))
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3378, in check
    return check_verbose(obj, is_inlined_call).skipped
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3361, in check_verbose
    rule = torch._dynamo.trace_rules.lookup_inner(
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3442, in lookup_inner
    rule = get_torch_obj_rule_map().get(obj, None)
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2782, in get_torch_obj_rule_map
    obj = load_object(k)
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2811, in load_object
    val = _load_obj_from_str(x[0])
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\_dynamo\trace_rules.py", line 2795, in _load_obj_from_str
    return getattr(importlib.import_module(module), obj_name)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\nested\_internal\nested_tensor.py", line 417, in <module>
    values=torch.randn(3, 3, device="meta"),
C:\Users\username\Downloads\Programs\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\nested\_internal\nested_tensor.py:417: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  values=torch.randn(3, 3, device="meta"),
Traceback (most recent call last):
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\cutie_roto.py", line 21, in <module>
    from gui.main_controller import MainController
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\gui\main_controller.py", line 24, in <module>
    from gui.interactive_utils import torch_prob_to_numpy_mask, index_numpy_to_one_hot_torch, get_visualization, get_visualization_torch
  File "C:\Users\username\Downloads\Programs\Cutie-Roto\gui\interactive_utils.py", line 47, in <module>
    color_map_torch = torch.from_numpy(color_map_np).to(device) / 255
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available
Press any key to continue . . .```

**Comment by Zarxrax** [comment]
Hi, I just did a clean install, and did not encounter any errors. Also it should be fully compatible with Numpy 2.
I would need more information to determine why you might be seeing this error.
What exact steps did you take to install and run the application?
At what point did the error occur? Did anything launch before you saw the error?

**Comment by Maris495** [comment]
First I had installed the dependencies, but somehow it was in this weird state that the progress bars for downloading the requirements are 100% but the message says that they are installing them. I don't know if they were complete or not, so I exited the CMD. Then I tried to run Cutie Roto, but I got into an error that some dependencies are missing. So I had to restart the dependencies installation again, and the installation was complete. So I tried to run Cutie Roto again, but I got this error that says "A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.0 as it may crash." Tried reinstalling it again, still the same error.

**Comment by Zarxrax** [comment]
I think you may need to delete the entire cutie-roto folder then start over. It sounds like one of the dependencies may have gotten corrupted.

**Comment by Maris495** [comment]
I did it and I still got the same error.

**Comment by Zarxrax** [comment]
I was able to reproduce this now when installing the cpu version. I'll try to look into a fix soon.

**Comment by Maris495** [comment]
I hope there's a solution to it soon.

**Comment by Zarxrax** [comment]
Please try this new version: https://github.com/Zarxrax/Cutie-Roto/releases/tag/v0.5.3-rc1

**Comment by Maris495** [comment]
I've installed the new version, but I got another error when trying to run it.

``` 
Traceback (most recent call last):
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\cutie_roto.py", line 24, in <module>
    from gui.main_controller import MainController
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\gui\main_controller.py", line 24, in <module>
    from gui.interactive_utils import torch_prob_to_numpy_mask, index_numpy_to_one_hot_torch, get_visualization, get_visualization_torch
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\gui\interactive_utils.py", line 32, in <module>
    if cfg.force_cpu:
       ^^^^^^^^^^^^^
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\python-3.11.7-embed-amd64\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
omegaconf.errors.ConfigAttributeError: Key 'force_cpu' is not in struct
    full_key: force_cpu
    object_type=dict ```

**Comment by Zarxrax** [comment]
Whoops, looks like I accidentally included an old config file in the package.
[gui_config.zip](https://github.com/user-attachments/files/16741947/gui_config.zip)

Extract the attached file into your Cutie-Roto\cutie\config  folder, and that should fix it.

**Comment by Zarxrax** [comment]
Or actually just wait a few minutes and I will upload another update on the releases page. It looks like some other files in the package might be outdated as well.

**Comment by Zarxrax** [comment]
https://github.com/Zarxrax/Cutie-Roto/releases/tag/v0.5.3-rc2

**Comment by Maris495** [comment]
I got another error, but at least this one has a few lines
```
Traceback (most recent call last):
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\cutie_roto.py", line 24, in <module>
    from gui.main_controller import MainController
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\gui\main_controller.py", line 30, in <module>
    from scripts.download_models import download_models_if_needed
  File "C:\Users\username\Downloads\Programs\CutieRoto_clean\scripts\download_models.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Maris495** [comment]
The software finally works! Thanks for helping me!
